-- Conformed date dimension, loaded verbatim from Batch1/Date.txt.
select
  sk_dateid,
  datevalue,
  datedesc,
  calendaryearid,
  calendaryeardesc,
  calendarqtrid,
  calendarqtrdesc,
  calendarmonthid,
  calendarmonthdesc,
  calendarweekid,
  calendarweekdesc,
  dayofweeknum,
  dayofweekdesc,
  fiscalyearid,
  fiscalyeardesc,
  fiscalqtrid,
  fiscalqtrdesc,
  holidayflag_raw in ('1', 'true', 'True', 't', 'Y') as holidayflag
from {{ read_pipe('Batch1/Date.txt',
  "{'sk_dateid': 'BIGINT', 'datevalue': 'DATE', 'datedesc': 'VARCHAR',
    'calendaryearid': 'INTEGER', 'calendaryeardesc': 'VARCHAR',
    'calendarqtrid': 'INTEGER', 'calendarqtrdesc': 'VARCHAR',
    'calendarmonthid': 'INTEGER', 'calendarmonthdesc': 'VARCHAR',
    'calendarweekid': 'INTEGER', 'calendarweekdesc': 'VARCHAR',
    'dayofweeknum': 'INTEGER', 'dayofweekdesc': 'VARCHAR',
    'fiscalyearid': 'INTEGER', 'fiscalyeardesc': 'VARCHAR',
    'fiscalqtrid': 'INTEGER', 'fiscalqtrdesc': 'VARCHAR',
    'holidayflag_raw': 'VARCHAR'}") }}
